### ISSUE TITLE
'type' object is not iterable

### ISSUE THREAD

**Issue by cheo2322** [dark-lbp/isf#4]
I am trying to run it, but I get this:

python isf.py
Traceback (most recent call last):
  File "isf.py", line 9, in <module>
    from icssploit.interpreter import IcssploitInterpreter
  File "/root/isf/icssploit/__init__.py", line 1, in <module>
    from icssploit.utils import (
  File "/root/isf/icssploit/utils/__init__.py", line 21, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable

**Comment by FraggleR0ck** [comment]
Did you install the required libraries in the requirements.txt file?

**Comment by dark-lbp** [comment]
@cheo2322  I'm closing the issue, if you still have problems with it, please reply :)
