### ISSUE TITLE
no module nmap

### ISSUE THREAD

**Issue by engineerash** [dark-lbp/isf#8]
Traceback (most recent call last):
  File "isf.py", line 9, in <module>
    from icssploit.interpreter import IcssploitInterpreter
  File "/root/Desktop/isf/icssploit/__init__.py", line 1, in <module>
    from icssploit.utils import (
  File "/root/Desktop/isf/icssploit/utils/__init__.py", line 15, in <module>
    import nmap
ImportError: No module named nmap

**Comment by payne747** [comment]
Tried `sudo apt-get install python-nmap`?
(assuming Debian based distro)

**Comment by Laldoma** [comment]
ICSS does not work in kali since 2020.1

**Comment by Jackson-Pollock** [comment]
I am able to fix this using pip install python-nmap==0.6.4
(older version)
